var searchData=
[
  ['bad_5falloc_0',['bad_alloc',['../classkerbal_1_1memory_1_1bad__alloc.html',1,'kerbal::memory']]],
  ['bad_5fany_5fcast_1',['bad_any_cast',['../classkerbal_1_1any_1_1bad__any__cast.html',1,'kerbal::any']]],
  ['bad_5farray_5fnew_5flength_2',['bad_array_new_length',['../classkerbal_1_1memory_1_1bad__array__new__length.html',1,'kerbal::memory']]],
  ['bad_5ffunction_5fcall_3',['bad_function_call',['../classkerbal_1_1function_1_1bad__function__call.html',1,'kerbal::function']]],
  ['bad_5ffunction_5fcast_4',['bad_function_cast',['../classkerbal_1_1function_1_1bad__function__cast.html',1,'kerbal::function']]],
  ['bad_5foptional_5faccess_5',['bad_optional_access',['../classkerbal_1_1optional_1_1bad__optional__access.html',1,'kerbal::optional']]],
  ['basic_5fany_6',['basic_any',['../classkerbal_1_1any_1_1basic__any.html',1,'kerbal::any']]],
  ['basic_5ffunction_7',['basic_function',['../classkerbal_1_1function_1_1basic__function.html',1,'kerbal::function']]],
  ['basic_5ffunction_3c_20ret_28targs_2e_2e_2e_29_2c_20size_2c_20align_2c_20allocator_20_3e_8',['basic_function&lt; Ret(TArgs...), Size, Align, Allocator &gt;',['../classkerbal_1_1function_1_1basic__function_3_01_ret_07_t_args_8_8_8_08_00_01_size_00_01_align_00_01_allocator_01_4.html',1,'kerbal::function']]],
  ['basic_5fmove_5fonly_5ffunction_9',['basic_move_only_function',['../classkerbal_1_1function_1_1basic__move__only__function.html',1,'kerbal::function']]],
  ['basic_5fmove_5fonly_5ffunction_3c_20ret_28targs_2e_2e_2e_29_2c_20size_2c_20align_2c_20allocator_20_3e_10',['basic_move_only_function&lt; Ret(TArgs...), Size, Align, Allocator &gt;',['../classkerbal_1_1function_1_1basic__move__only__function_3_01_ret_07_t_args_8_8_8_08_00_01_size_00_01_align_00_01_allocator_01_4.html',1,'kerbal::function']]],
  ['basic_5ft_11',['basic_t',['../structkerbal_1_1memory_1_1basic__t.html',1,'kerbal::memory']]],
  ['bernoulli_5fdistribution_12',['bernoulli_distribution',['../classkerbal_1_1random_1_1bernoulli__distribution.html',1,'kerbal::random']]],
  ['binomial_5fdistribution_13',['binomial_distribution',['../classkerbal_1_1random_1_1binomial__distribution.html',1,'kerbal::random']]],
  ['bitarray_5fresult_14',['bitarray_result',['../structkerbal_1_1numeric_1_1bitarray__result.html',1,'kerbal::numeric']]],
  ['bitarray_5fresult_5flen_15',['bitarray_result_len',['../structkerbal_1_1numeric_1_1bitarray__result__len.html',1,'kerbal::numeric']]],
  ['bitset_5fbits_5fper_5fblock_16',['bitset_bits_per_block',['../structkerbal_1_1bitset_1_1detail_1_1bitset__bits__per__block.html',1,'kerbal::bitset::detail']]],
  ['bitset_5fsize_5funrelated_17',['bitset_size_unrelated',['../classkerbal_1_1bitset_1_1detail_1_1bitset__size__unrelated.html',1,'kerbal::bitset::detail']]],
  ['bool_5fconstant_18',['bool_constant',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20alloc_3a_3aallow_5fdeallocate_5fnull_3a_3avalue_20_3e_19',['bool_constant&lt; Alloc::allow_deallocate_null::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20alloc_3a_3ais_5falways_5fequal_3a_3avalue_20_3e_20',['bool_constant&lt; Alloc::is_always_equal::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20alloc_3a_3apropagate_5fon_5fcontainer_5fcopy_5fassignment_3a_3avalue_20_3e_21',['bool_constant&lt; Alloc::propagate_on_container_copy_assignment::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20alloc_3a_3apropagate_5fon_5fcontainer_5fmove_5fassignment_3a_3avalue_20_3e_22',['bool_constant&lt; Alloc::propagate_on_container_move_assignment::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20alloc_3a_3apropagate_5fon_5fcontainer_5fswap_3a_3avalue_20_3e_23',['bool_constant&lt; Alloc::propagate_on_container_swap::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20arg_3a_3avalue_3d_3d_2d1_20_3e_24',['bool_constant&lt; Arg::value==-1 &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20arg_3a_3avalue_3d_3d0_20_3e_25',['bool_constant&lt; Arg::value==0 &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20arg_3a_3avalue_3d_3d1_20_3e_26',['bool_constant&lt; Arg::value==1 &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20false_20_3e_27',['bool_constant&lt; false &gt;',['../structkerbal_1_1type__traits_1_1bool__constant_3_01false_01_4.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20kerbal_3a_3aiterator_3a_3ais_5fbidirectional_5fcompatible_5fiterator_3c_20tp_20_3e_3a_3avalue_7c_7ckerbal_3a_3aiterator_3a_3ais_5fforward_5fiterator_3c_20tp_20_3e_3a_3avalue_20_3e_28',['bool_constant&lt; kerbal::iterator::is_bidirectional_compatible_iterator&lt; Tp &gt;::value||kerbal::iterator::is_forward_iterator&lt; Tp &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20kerbal_3a_3aiterator_3a_3ais_5fforward_5fcompatible_5fiterator_3c_20tp_20_3e_3a_3avalue_7c_7ckerbal_3a_3aiterator_3a_3ais_5finput_5fiterator_3c_20tp_20_3e_3a_3avalue_20_3e_29',['bool_constant&lt; kerbal::iterator::is_forward_compatible_iterator&lt; Tp &gt;::value||kerbal::iterator::is_input_iterator&lt; Tp &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20kerbal_3a_3aiterator_3a_3ais_5frandom_5faccess_5fcompatible_5fiterator_3c_20tp_20_3e_3a_3avalue_7c_7ckerbal_3a_3aiterator_3a_3ais_5fbidirectional_5fiterator_3c_20tp_20_3e_3a_3avalue_20_3e_30',['bool_constant&lt; kerbal::iterator::is_random_access_compatible_iterator&lt; Tp &gt;::value||kerbal::iterator::is_bidirectional_iterator&lt; Tp &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fabstract_3c_20t_20_3e_3a_3avalue_20_3e_31',['bool_constant&lt; std::is_abstract&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fassignable_3c_20t_2c_20u_20_3e_3a_3avalue_20_3e_32',['bool_constant&lt; std::is_assignable&lt; T, U &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fbase_5fof_3c_20base_2c_20derived_20_3e_3a_3avalue_20_3e_33',['bool_constant&lt; std::is_base_of&lt; Base, Derived &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fclass_3c_20t_20_3e_3a_3avalue_20_3e_34',['bool_constant&lt; std::is_class&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fempty_3c_20t_20_3e_3a_3avalue_20_3e_35',['bool_constant&lt; std::is_empty&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fenum_3c_20t_20_3e_3a_3avalue_20_3e_36',['bool_constant&lt; std::is_enum&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5ffinal_3c_20t_20_3e_3a_3avalue_20_3e_37',['bool_constant&lt; std::is_final&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fscalar_3c_20t_20_3e_3a_3avalue_20_3e_38',['bool_constant&lt; std::is_scalar&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5fstandard_5flayout_3c_20t_20_3e_3a_3avalue_20_3e_39',['bool_constant&lt; std::is_standard_layout&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20std_3a_3ais_5funion_3c_20t_20_3e_3a_3avalue_20_3e_40',['bool_constant&lt; std::is_union&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20tp_3a_3avalue_20_3e_41',['bool_constant&lt; Tp::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_20true_20_3e_42',['bool_constant&lt; true &gt;',['../structkerbal_1_1type__traits_1_1bool__constant_3_01true_01_4.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_21is_5ffundamental_3c_20t_20_3e_3a_3avalue_20_3e_43',['bool_constant&lt;!is_fundamental&lt; T &gt;::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]],
  ['bool_5fconstant_3c_21tp_3a_3avalue_20_3e_44',['bool_constant&lt;!Tp::value &gt;',['../structkerbal_1_1type__traits_1_1bool__constant.html',1,'kerbal::type_traits']]]
];
